### ISSUE TITLE
Question about thrshld_b()

### ISSUE THREAD

**Issue by jorisbertrand** [HemingNM/ENMwizard#1]
Good morning, 
and first of all, thanks for this great package!
We were trying to reproduce the tutorial with our data and came across a small problem with the thrshld_b() function with the following error message:
_mods.thrshld.lst <- thrshld_b(mxnt.mdls.preds.cf, thrshld.i = c(5,7)) 
_“Error_ in FUN(X[[i]], ...) : tentative d’obtenir le slot “results” d’un objet d’une classe élémentaire (“NULL”) sans slots”._
Sorry, it is in French but it looks like the function is looking for a result slot within the object. Is there something related to the function or do we have to precise on which part the mxnt.mdls.preds.cf object we want to apply the threshold?
Thank you for your help

**Comment by willright28** [comment]
Hi @jorisbertrand 
Have you solve this question?
I have the same problem when try to apply 'thrshld_b' to my data. 
I followed every steps instructed by mannul and work almost well expect the threshold step, and stuck there.
BTW the example data worked fine.
Thanks in advance

**Comment by jorisbertrand** [comment]
Hi @willright28 
Not yet. We are not sure on what to take within the mxnt.mdls.preds.cf object. 
Keep in touch

**Comment by HemingNM** [comment]
Hi @jorisbertrand and @willright28. Sorry for not answering before.
I added some functions to compute consensus projections (consensus_scn_b) that broke the 'threshold_b' function when consensus projections were not available. I've updated 'threshold_b' function and now should work fine. Try reinstalling the package and please, let me know if you have any issue or feature you would like to see in the package.
Best

**Comment by jorisbertrand** [comment]
Thank you for your answer. 
We are just not sure to understand what the ‘group’ argument stands for. In our case, we would like to obtain three distinct projections, one for current climate, one for a 2050 projection and one for a 2070 projection. So far, we only tested one CGM and RCP level.

**Comment by HemingNM** [comment]
You don't need consensual projections, just skip that. You would need if you had more than one GCM for each year and/or RCP (e.g. three for 2050 at RCP 4.5, three for 2050 at RCP 8.5, and the same for 2070).

**Comment by jorisbertrand** [comment]
Well, its seems that the function requires a 'group' argument...

**Comment by willright28** [comment]
It works well know，you could have a try


 
---Original---
From: "Joris ***@***.***&gt;
Date: 2021/4/13 19:52:13
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HemingNM/ENMwizard] Question about thrshld_b() (#1)




 
Well, its seems that the function requires a 'group' argument...

**Comment by jorisbertrand** [comment]
No it doesn't. But maybe we are doing something wrong...
No worries, we will find a way to do want we want do do anyway.
Cheers

**Comment by HemingNM** [comment]
Hi, [hopefully] fixed last bug. Also updated the readme to include one example of how to compute a consensual projection.
Reinstall, unload, and then load the package again and see if it runs:
devtools::install_github("HemingNM/ENMwizard")
detach("package:ENMwizard", unload = TRUE)
library(ENMwizard)
Cheers

**Comment by jorisbertrand** [comment]
OK, thanks again for your help.
It seems that now the commands: 
> consensus <- consensus_scn_b(mxnt.mdls.preds.cf, groups = FALSE)
works, but it outputs a unique projection made from of three scenario (current climate, 2050, 2070).
> mods.thrshld.lst <- thrshld_b(consensus, thrshld.i = c(5,7))
the second lines still does not work:
“Error in FUN(X[[i]], ...) : tentative d’obtenir le slot “results” d’un objet d’une classe élémentaire (“NULL”) sans slots”.

**Comment by HemingNM** [comment]
You need to specify correctly how projections will be grouped for computing consensual projections. 'groups' argument is set to FALSE, which will not return any group from your projections:
`consensus <- consensus_scn_b(mxnt.mdls.preds.cf, groups = FALSE)`

Check if groups are correctly assigned before computing consensual projections:
1. Create two vectors containing grouping codes
`yr <- c(50, 70)
`
`rcp <- c("45", "85")
`
2. Store names of climate scenarios
`clim.scn.nms <- names(predictors.l)
`
or
`clim.scn.nms <- names(mxnt.mdls.preds.cf[[1]]$mxnt.preds)
`
3. Then see the difference between usage of argument 'groups'
`consensus_gr(groups=F, clim.scn.nms)
`
`consensus_gr(groups=list(yr, rcp), clim.scn.nms)
`
4. If the groups are correctly assigned then you compute the consensual projections
`mxnt.mdls.preds.cf <- consensus_scn_b(mcmp.l=mxnt.mdls.preds.cf, groups = list(yr, rcp))
`
5. finally use 'thrshld_b' 
`mods.thrshld.lst <- thrshld_b(consensus, thrshld.i = c(5,7))
`

**Comment by jorisbertrand** [comment]
Hi, still have the same problem:
> mods.thrshld.lst <- thrshld_b(mxnt.mdls.preds.cf, thrshld.i = c(5,7))
Error in FUN(X[[i]], ...) : 
  trying to get slot "results" from an object of a basic class ("NULL") with no slots

According to help, 
thrshld_b(mcmp.l, thrshld.i = 4:6, t.all = FALSE, numCores = 1)
mcmp.l | Object returned by proj_mdl_b, containing a list of calibrated models and model projections for each species.

In my case, I have one current model and four future projections (I don't want to get consensus) in mxnt.mdls.preds.cf but it is like if the function could not get the wright slot(s) in this object.

Cheers

**Comment by HemingNM** [comment]
It is very likely that the wrongly calculated 'scn.consensus' slot is still there. If you calculated but don't want it anymore, just erase it and the function will work fine:
`mxnt.mdls.preds.cf[[1]]$scn.consensus <- NULL`
`mxnt.mdls.preds.cf[[1]]$scn.consensus.sd <- NULL`
Cheers

**Comment by jorisbertrand** [comment]
Both are empty already:
> mxnt.mdls.preds.cf[[1]]$scn.consensus
NULL
> mxnt.mdls.preds.cf[[1]]$scn.consensus.sd
NULL
Just to be sure that we are talking about the same thing, is there a way to 'Apply thresholds on suitability projections' without doing what is described in 'Create consensual projections across GCMs by (e.g.) year and/or RCP'? I would like to apply thresholds on suitability projections independently on my current model and four future climate projections. But if I do:
> mxnt.mdls.preds.cf <- consensus_scn_b(mcmp.l=mxnt.mdls.preds.cf, groups = FALSE)
> mods.thrshld.lst <- thrshld_b(mxnt.mdls.preds.cf, thrshld.i = c(5,7))
It does not work... (or only the second command line). As @willright28 mentioned, it seems to work with the example data set but not with all data sets.
Cheers

**Comment by HemingNM** [comment]
Yes, you can apply threshold on individual projections!
Try updating the package, I have made some changes yesterday.
Keep in touch

**Comment by willright28** [comment]
Hi Bertrand
Try unistall package completely and restart R session，then install it as instruction，it worked for my own data set now


cheers


 
---Original---
From: "Joris ***@***.***&gt;
Date: 2021/4/16 00:46:04
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HemingNM/ENMwizard] Question about thrshld_b() (#1)




 
Both are empty already:
  
mxnt.mdls.preds.cf[[1]]$scn.consensus
 NULL
 mxnt.mdls.preds.cf[[1]]$scn.consensus.sd
 NULL
 Just to be sure that we are talking about the same thing, is there a way to 'Apply thresholds on suitability projections' without doing what is described in 'Create consensual projections across GCMs by (e.g.) year and/or RCP'? I would like to apply thresholds on suitability projections independently on my current model and four future climate projections. But if I do:
 mxnt.mdls.preds.cf <- consensus_scn_b(mcmp.l=mxnt.mdls.preds.cf, groups = FALSE)
 mods.thrshld.lst <- thrshld_b(mxnt.mdls.preds.cf, thrshld.i = c(5,7))
 It does not work... (or only the second command line). As @willright28 mentioned, it seems to work with the example data set but not with all data sets.
 Cheers

**Comment by willright28** [comment]
Hi @Heming
How to understand the 'consensus_scn_b' function？Does it combine every input layer，then make a stability map including pixels that only were predicted "suitable" by group we definded(e.g. by year from history to future)?


Thanks in advance!
BEST


 
---Original---
From: "Neander Marcel ***@***.***&gt;
Date: 2021/4/16 01:29:24
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HemingNM/ENMwizard] Question about thrshld_b() (#1)




 
Yes, you can apply threshold on individual projections!
 Try updating the package, I have made some changes yesterday.
 Keep in touch

**Comment by HemingNM** [comment]
Hi @willright28, the function's purpose is to compute consensus among GCMs for a projection year and/or RCP. So, it takes only the layers indicated by each group and computes the average suitability value for each pixel. You can find more about consensus (pros and cons) in these publications:
- https://doi.org/10.1002/ece3.1411
- https://doi.org/10.1111/j.1461-0248.2008.01231.x
- https://doi.org/10.1111/2041-210X.13360

Best

**Comment by HemingNM** [comment]
> Hi, still have the same problem:
> 
> > mods.thrshld.lst <- thrshld_b(mxnt.mdls.preds.cf, thrshld.i = c(5,7))
> > Error in FUN(X[[i]], ...) :
> > trying to get slot "results" from an object of a basic class ("NULL") with no slots
> 
> According to help,
> thrshld_b(mcmp.l, thrshld.i = 4:6, t.all = FALSE, numCores = 1)
> mcmp.l | Object returned by proj_mdl_b, containing a list of calibrated models and model projections for each species.
> 
> In my case, I have one current model and four future projections (I don't want to get consensus) in mxnt.mdls.preds.cf but it is like if the function could not get the wright slot(s) in this object.
> 
> Cheers

Hi @jorisbertrand , just corrected a small bug that could have been causing this issue in few circumstances. Cheers

**Comment by jorisbertrand** [comment]
Dear @HemingNM,
thanks a lot! We will try to install the last version of the package. Actually we did realize that the appearance of the error message was dependent on the input environmental layers. It did not work with data with a resolution of 2.5° but then worked fine with data whose resolution was 0.5° (both downloaded with the get data() function from worlclim). So perhaps there is something to do with a minimum amount a ecological data required for a given geographic extent...
