### ISSUE TITLE
How to fix the problem of no slot of name "occ.pts" for this object of class "ENMevaluation"

### ISSUE THREAD

**Issue by futurefanzhang** [HemingNM/ENMwizard#10]
Hi Neander Marcel Heming,

I'm using your package ENMwizard. When I use the function calib_mdl_b. there is one problem "no slot of name "occ.pts" for this object of class "ENMevaluation" I checked the ENMevaluate_b function. The occ.pts related content is set as explanatory note. How can I fix this problem?

**Comment by HemingNM** [comment]
Hi @futurefanzhang ,

this is likely related to the version of ENMeval. Versions above 1.0 are not yet supported by ENMwizard. 
To install an older version:
```
library(devtools)
detach("package:ENMeval", unload=TRUE)
install_version("ENMeval", version = "0.3.1")
````
After this, probably you need to run ENMevaluate_b() again.
Let me know if it works.

Best,
Neander

**Comment by futurefanzhang** [comment]
Thank you very much. Now it works!
