### ISSUE TITLE
ENMevaluate_b wrong

### ISSUE THREAD

**Issue by willright28** [HemingNM/ENMwizard#3]
Hi @HemingNM 
I updated ENMeval package from v0.3 to v 2.0, then when funtion 'ENMevaluate_b ' was applied, it gave error message 'Error in ENMeval::ENMevaluate(occ.l[[i]], a.calib.l[[i]], bg.coords = bg.coords.l[[i]],  : Parameter useless(aggregation.factor = aggregation.factor, kfolds = kfolds)'
I noticed the ENMeval package was updated recently(2021-05-19), is it the reason that which is incompatible with ENMwizard now?
Though it's ok to use former version of ENMeval.
BTW, sometimes the funtion 'thrshld_b' failed again, it's weird, because #1 have discussed it a lot and I've used it successfully many times...

Thanks in advance!

**Comment by willright28** [comment]
‘thrshld_b’ gave : "Error in grepl(outpt, rownames(mxnt.mdls[[1]]@results), ignore.case = T) :  'pattern'Parameters are wrong"

**Comment by HemingNM** [comment]
Hi @willright28, 
thank you for reporting the issue. Yes, the last update changed arguments of ENMevaluate function as well the output structure. I have some work ahead to make ENMwizard compatible with both versions. For now, it is fine to use the previous version, as most of it's internal methods remain the same.
Can you send me more details (arguments used in thrshld_b and previous functions) so that I can figure out what is happening. Preferably some reproducible example of the error.
Best!

**Comment by willright28** [comment]
I followed every step of your instructions, using a consensual projection, for example the 2070-RCP85:

predictors.l.8570 <- list(current = envi_bio19_curr,
                          futcn8570 = futcn8570,
                          futmc8570 = futmc8570,
                          futcc8570 = futcc8570,
                          futmp8570 = futmp8570)
mxnt.mdls.preds.cf.8570 <- proj_mdl_b(mxnt.mdls.preds.lst, a.proj.l = pred.cut.l.8570)
sce <- c("8570")
groups <- list(sce)
clim.scn.nms.8570 <- names(predictors.l.8570)
consensus_gr(groups, clim.scn.nms.8570)
mxnt.mdls.preds.cf.8570 <- consensus_scn_b(mcmp.l=mxnt.mdls.preds.cf.8570, groups = list(sce),ref="current")
mods.thrshld.lst.8570 <- thrshld_b(mxnt.mdls.preds.cf.8570, thrshld.i = c(5,7))

But it just can not work now...

**Comment by HemingNM** [comment]
Hi @willright28,
I just ran the tutorial without issues. Which model selection criteria did you use when calibrating the model? Are you using the latest version of the package? Remember not to use the new version of ENMeval. If you used it, you'll need to rerun model evaluation.
Best

**Comment by HemingNM** [comment]
I just made a small change that can fix your problem. Let me know if it works.

**Comment by willright28** [comment]
Hi @HemingNM 
I updated the package to the latest version, but now the funtion 'calib_mdl_b' failed...

'''
arguments used for building models 
  ID optimality.criteria settings
1  1              LowAIC     LP_1
2  2                         LQ_1
3  3                         LH_1

Error in stats::setNames(c(strsplit(args, ",")), mod.nms) : 
  Object not found 'mod.nms'
'''

This is the command I used:
 calib_mdl_b(ENMeval.o.l = ENMeval.res.lst, 
                                   a.calib.l = pred.cut, occ.l = occ.locs,
                                   mSel = c("LowAIC"),
                                   pred.args = c("randomtestpoints=20"),
                                   arg1 = "jackknife=true")

And yes I used v0.3.1 of ENMeval, so I don't need to rerun model evalution right?(I have hugu dataset and it'll take long time to rerun...), and still the 'thrshld_b' failed...

Thanks for your time.

**Comment by HemingNM** [comment]
Hi @willright28 ,
my guess is that the way 'pred.args' and 'arg1' are specified is causing your problem. A model is calibrated using all occ points. So, to calibrate your model, you should not use randomtestpoints, as the models were already tested with ENMeval. Remove these arguments and calib_mdl_b should run finely. Also, as this function did not run, the resulting object won't be compatible with the next functions, causing the error you had.

**Comment by willright28** [comment]
Hi @HemingNM 
I try example but stuck in the calib_mdl_b again, I'm pretty sure I followed every instruction steps, please check.

'''
Error in stats::setNames(c(strsplit(args, ",")), mod.nms) :
Object not found 'mod.nms'
'''

Thanks a lot.

**Comment by HemingNM** [comment]
Hi @willright28 
Just figured out that one minor change was missing. Sorry for that. Hopefully it will work now!
Also, I am working on to make the functions compatible with both versions of ENMeval.
Let me know of any issue or feature you would like to see implemented.
Best

**Comment by willright28** [comment]
Hi! @HemingNM
Apologize for reply you later, and thanks for all these modification! It works well now!
A little question is could I save the output of function 'plot_scn_diff_b' as a raster file?

**Comment by HemingNM** [comment]
Hi @willright28, 
Great to hear that it worked!
About 'plot_scn_diff_b', you cannot save as raster yet, but I am planning to implement it soon and make the output compatible with 'get_tsa_b' (or a similar function). It will be possible not only to plot, but also 'get the numbers' of change (gain/loss) in suitable area between climate scenarios.

**Comment by HemingNM** [comment]
Hi @willright28,
Just added functions to save the rasters of range shifts (range differences between climate scenarios; range_shift_b) and to compute the total amount of area that remained unchanged, was lost and gained between scenarios (get_rsa_b).
Let me know if you find them useful and if you find any issue.
Cheers

**Comment by willright28** [comment]
Glad to know this！I will try those functions as soon as possible，thanks a lot！



---Original---
From: "Neander Marcel ***@***.***&gt;
Date: Fri, Jul 16, 2021 19:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HemingNM/ENMwizard] ENMevaluate_b wrong (#3)




 
Hi @willright28,
 Just added functions to save the rasters of range shifts (range differences between climate scenarios; range_shift_b) and to compute the total amount of area that remained unchanged, was lost and gained between scenarios (get_rsa_b).
 Let me know if you find them useful and if you find any issue.
 Cheers
