### ISSUE TITLE
Evaluate model performance

### ISSUE THREAD

**Issue by willright28** [HemingNM/ENMwizard#4]
Hi @HemingNM:
This question is about how to evaluate model performance.
May I ask how to get the true skill statistics(TSS) of the final model? Because I was asked to assess  whether my final best model(selected based on "LowAIC") can be able to discriminate between background and presence points. As I know the ENMwizard only have three criterion to directly assess model performance in the output: "train.AUC", "avg.test.orMTP", and "avg.test.or10pct", but without TSS.
Thanks in advance!

**Comment by HemingNM** [comment]
Hi @willright28, 
you can evaluate the desired maxent model using function evaluate() from dismo package and occurrences and background points. It will generate a confusion matrix for several threshold values that you will need to compute TSS.
`
dismo::evaluate(occ, bg, model)@confusion
`
TSS formula can be found in [Allouche et al 2006](doi.org/10.1111/j.1365-2664.2006.01214.x).
As this is not an issue from the package, I'll close it. Let me know if you need further help through my email: neanderh at yahoo.com.br
Best

**Comment by willright28** [comment]
Thanks for your reply.
I've find out how to export the background prediction and calculate TSS.
Sorry for not closing this issue immediately.



---Original---
From: "Neander Marcel ***@***.***&gt;
Date: Mon, Dec 20, 2021 22:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HemingNM/ENMwizard] Evaluate model performance (Issue #4)




 
Hi @willright28,
 you can evaluate the desired maxent model using function evaluate() from dismo package and occurrences and background points. It will generate a confusion matrix for several threshold values that you will need to compute TSS.
 dismo::evaluate(occ, bg, ***@***.***
 TSS formula can be found in Allouche et al 2006.
 As this is not an issue from the package, I'll close it. Let me know if you need further help through my email: neanderh at yahoo.com.br
 Best
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
