### ISSUE TITLE
Error message with the ENMevaluate_b() function

### ISSUE THREAD

**Issue by jorisbertrand** [HemingNM/ENMwizard#5]
Dear Neander,
thank you again for this great tool that ENM Wizard is. I am trying to use your package on a new dataset and got the following error message while trying to run ENMevaluate_b():

Error in ENMeval::ENMevaluate(occ.l[[i]], a.calib.l[[i]], bg.coords = bg.coords.l[[i]],  : 
  unused arguments (aggregation.factor = aggregation.factor, kfolds = kfolds)

The exact command line I used was: 

ENMeval.res.lst <- ENMevaluate_b(occ.locs, pred.cut, RMvalues = seq(0.5, 4.5, 0.5), fc = c("L", "P", "Q", "H", "LP", "LQ", "LH", "PQ", "PH", "QH", "LPQ", "LPH", "LQH", "PQH", "LPQH"), method="block", algorithm="maxent.jar")

I came across this closed [issue](https://github.com/HemingNM/ENMwizard/issues/3) which suggest that it may have something to do with a recent update of ENMeval. Do you think this could be the case?

Cheers,
Joris

**Comment by gabferreira** [comment]
Hi Joris,

I've had this error before and to solve it I installed an older version (0.3.1) of ENMeval using the commands below:

library(devtools)
detach("package:ENMeval", unload=TRUE)
install_version("ENMeval", version = "0.3.1")

I hope it helps!

Best Regards,
Gabriela

**Comment by jorisbertrand** [comment]
Hi Grabriela!
Thanks a lot. Indeed I could solve the problem but did not have time to give some fresh news here.
Cheers,
Joris

**Comment by HemingNM** [comment]
Hi @jorisbertrand, this indeed is a problem of compatibility with the new version of ENMeval. Thank you @gabferreira for pointing out a solution.
Cheers
