### ISSUE TITLE
Error: Error writing feature weights file

### ISSUE THREAD

**Issue by jorisbertrand** [HemingNM/ENMwizard#6]
Hi, 
sorry to bother you again but now it seems that I cannot save the output of the calibration models:
Error: Error writing feature weights file
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '3_out.MaxEnt/Mdls.Bvarieg/cloglog/Mod_1.5_L/species.lambdas': No such file or directory
Indeed the folder /Mod_1.5_L/ exists but only contains the 'absent', 'maxent.log', 'maxentResults.csv' (which is empty) and 'presence' files.
Does any body know how to solve that?
All the best,
Joris

**Comment by jorisbertrand** [comment]
Just upgraded R and all the associated packages (except ENMeval) and it runs now ;-).

**Comment by HemingNM** [comment]
Hi @jorisbertrand,
I was out of office, did not follow the issues last weeks. Great you figured out how to solve it. 
Let me know whenever you find any issue.
Cheers
