### ISSUE TITLE
ENMeval.res.lst  error

### ISSUE THREAD

**Issue by chenyongpeng1** [HemingNM/ENMwizard#7]
HELO,SIR: when I run this code:
ENMeval.res.lst <- ENMevaluate_b(occ.locs, pred.cut, 
                                 RMvalues = c(1, 1.5), fc = c("L", "LQ", "LP"),
                                 method="block", algorithm="maxent.jar")
Error in ENMeval::ENMevaluate(occ.l[[i]], a.calib.l[[i]], bg.coords = bg.coords.l[[i]],  : 
  unused arguments (aggregation.factor = aggregation.factor, kfolds = kfolds)
  how to solve it?thanks!

**Comment by HemingNM** [comment]
Dear @chenyongpeng1,
This is because of the new version of ENMeval. The name of several arguments have changed. Try this out:
```
detach("package:ENMeval", unload=TRUE)
install_version("ENMeval", version = "0.3.1")
```
Let me know if it solved your issue.
Best,

**Comment by chenyongpeng1** [comment]
Great! Solved it! many thanks,sir!

best,chen yongpeng
