### ISSUE TITLE
Error in argument is of length zero

### ISSUE THREAD

**Issue by chenyongpeng1** [HemingNM/ENMwizard#8]
Dear SIR:
my study extent is world,but when I run this code,it is error!could you please tell me how to solve it?
> proj.extent <- extent(c(-180, 180, -90, 90))
> pred.cut.l <- cut_projarea_rst_mscn_b(proj.extent, predictors.l, occ.polys)

 Creating projection area 
Error in if (!datatype %in% c("LOG1S", "INT1S", "INT2S", "INT4S", "INT1U",  : 
  argument is of length zero

**Comment by HemingNM** [comment]
Dear @chenyongpeng1,
try coercing the extent object into SpatialPolygons
```
# coerce to a SpatialPolygons object
proj.extent <- as(proj.extent, 'SpatialPolygons') 
```
