### ISSUE TITLE
Error while running select_vars_b()

### ISSUE THREAD

**Issue by jorisbertrand** [HemingNM/ENMwizard#9]
Hi!
I get the following error while running the function select_vars_b(). It seems that it does not impede to run the rest of the script, but I do not understand this error. In the folder, I have a filed called envData.Oav.grd but not envDataSel.Oav.grd. Any idea of what it could be?
Cheers,
Joris

Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object '2_envData/area.calib/envDataSel.Oav.grd' of mode 'function' was not found

**Comment by HemingNM** [comment]
Hi Joris!
I did not see this error before. I have seen some errors if you run the function select_vars_b() twice on the same object (because some variables are dropped in the first time and not found on the next time).
Can you check this?
Cheers,
Neander

**Comment by jorisbertrand** [comment]
It seems that it could be because of the very last update of the package raster that breaks something (3.6-16). If I go back to the 3.6-14 it runs as usual.
I was having problems with the function raster::stack() that did not displayed cell values from rasters dowloaded from CHELSA in an expected way. The function terra::rast() gave me more consistent values but outputs an object of class SpatRaster (whereas raster::stack outputs an object of class RasterStack) which cannot further be used with ENMwizard...
I put the reference of the corresponding issue: https://github.com/rspatial/raster/issues/301
Will try to figure out what happens,
Cheers,

**Comment by HemingNM** [comment]
Hi Joris,
thank you for this information. The packages "rgeos" and "rgdal" will be retired from cran, so packages "sp" and "raster" are being modified to no longer depend on them.
I am planning to migrate ENMwizard to "terra" and also add support to the newer versions of "ENMeval". But, unfortunately I will be able to do this only after May. Sorry for that.
If you don't mind, please use older versions of "raster" and "ENMeval" while no updates are done.
Best,
Neander

**Comment by jorisbertrand** [comment]
Awesome! I will be glad to be among the beta testers of the new ENMWizard then! ;-)

**Comment by HemingNM** [comment]
Hi @jorisbertrand,
I have just tested select_vars_b() using latest versions of all packages (except for ENMeval). It runs finely.
Maybe, check your spatial datasets, try refreshing them (e.g. cutting again with 'cut_calibarea_b()').
Hope it works!
